services:
  hub:
    image: selenium/hub 
  chrome: 
    image: selenium/node-chromium
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env
  firefox: 
    image: selenium/node-firefox
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env